name: CI

on: [pull_request]

concurrency:
  group: ci-${{ github.event.pull_request.title }}
  cancel-in-progress: true

jobs:
  lint-styles:
    name: Lint Styles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - uses: bahmutov/npm-install@v1
      - run: cp .env.example .env
      - run: npm run lint
